#!/usr/bin/env python3
"""Refresh Kokoro frontend goldens from the reference misaki package.

This is development tooling only. The app and Swift test runner do not execute
Python; they consume the checked-in JSON fixture generated by this script.

Setup example:
  python3.12 -m venv /tmp/local-tts-misaki-venv
  /tmp/local-tts-misaki-venv/bin/python -m pip install "misaki[en]==0.9.4"
  /tmp/local-tts-misaki-venv/bin/python Scripts/generate-kokoro-frontend-goldens.py
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
from pathlib import Path
from typing import Any

from misaki import en


DEFAULT_FIXTURE = (
    Path(__file__).resolve().parents[1]
    / "Sources"
    / "LocalTTSTestRunner"
    / "Resources"
    / "KokoroFrontendGolden.json"
)


def build_g2p_cache() -> dict[bool, Any]:
    return {
        False: en.G2P(trf=False, british=False, fallback=None),
        True: en.G2P(trf=False, british=True, fallback=None),
    }


def refresh(path: Path) -> None:
    document = json.loads(path.read_text(encoding="utf-8"))
    g2ps = build_g2p_cache()

    document["source"] = {
        "name": "misaki",
        "version": importlib.metadata.version("misaki"),
        "api": "misaki.en.G2P(trf=False, british=<case.british>, fallback=None)",
        "generatedWith": "Scripts/generate-kokoro-frontend-goldens.py",
        "runtime": "development/test oracle only; the app does not run Python",
    }

    for case in document["cases"]:
        british = bool(case.get("british", False))
        phonemes, _ = g2ps[british](case["text"])
        case["phonemes"] = phonemes

    path.write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--fixture",
        type=Path,
        default=DEFAULT_FIXTURE,
        help="Path to KokoroFrontendGolden.json",
    )
    args = parser.parse_args()
    refresh(args.fixture)


if __name__ == "__main__":
    main()
